Send back empty JSON object for singletons.
icpctools/icpctools pull request #861
Opened 2024-03-17 10:11 UTC by nickygerritsen

Fixes #860.

This make it that when we don't have a singleton object, we return `{}`.
Does this make sense for all singletons?

2024-03-29 12:38 UTC, deboer-tim requested changes
I think this works for state, but is odd for things like the extended contest support, e.g. resolver and floor map - e.g. if I haven't configured a map it should probably be null; if I don't have access to the current resolving process running live then I probably shouldn't know it exists.

2024-03-29 12:39 UTC, nickygerritsen commented
> I think this works for state, but is odd for things like the extended contest support, e.g. resolver and floor map - e.g. if I haven't configured a map it should probably be null; if I don't have access to the current resolving process running live then I probably shouldn't know it exists.

So are you suggesting to hardcode the state check here?

2024-03-29 12:49 UTC, deboer-tim commented
> So are you suggesting to hardcode the state check here?

I think state probably needs a default/initial value in a contest.

2024-03-29 12:51 UTC, nickygerritsen commented
> > So are you suggesting to hardcode the state check here?
> 
> I think state probably needs a default/initial value in a contest.

Yeah that was my other idea. Feel free to implement that or I will try this at some point. Not sure (yet) where we would do this to get it working.

2024-03-30 09:27 UTC, nickygerritsen commented
Replaced by #875

2024-03-30 09:27 UTC, closed without merging